allow-branch = ["master"]
tag-prefix = "v"
tag-name = "v{{version}}"
sign-tag = false
sign-commit = false
publish = false
push = true

pre-release-hook = ["git", "cliff", "--tag", "v{{version}}", "--output", "CHANGELOG.md"]
